/**
 * Countries with ISO codes, dialing codes, currencies, and continents.
 * Used by the admin vendor invitation form for global onboarding.
 */

export interface CountryInfo {
  code: string;       // ISO 3166-1 alpha-2 (e.g. "IN", "AE", "US")
  name: string;       // Country name
  dialCode: string;   // International dialing code without "+" (e.g. "91", "971", "1")
  currency: string;   // ISO 4217 currency code (e.g. "INR", "AED", "USD")
  continent: string;  // Continent name
}

export const COUNTRIES: CountryInfo[] = [
  { code: "IN", name: "India", dialCode: "91", currency: "INR", continent: "Asia" },
  { code: "AE", name: "United Arab Emirates", dialCode: "971", currency: "AED", continent: "Asia" },
  { code: "US", name: "United States", dialCode: "1", currency: "USD", continent: "North America" },
  { code: "GB", name: "United Kingdom", dialCode: "44", currency: "GBP", continent: "Europe" },
  { code: "AU", name: "Australia", dialCode: "61", currency: "AUD", continent: "Oceania" },
  { code: "CA", name: "Canada", dialCode: "1", currency: "CAD", continent: "North America" },
  { code: "SG", name: "Singapore", dialCode: "65", currency: "SGD", continent: "Asia" },
  { code: "ZA", name: "South Africa", dialCode: "27", currency: "ZAR", continent: "Africa" },
  { code: "NG", name: "Nigeria", dialCode: "234", currency: "NGN", continent: "Africa" },
  { code: "KE", name: "Kenya", dialCode: "254", currency: "KES", continent: "Africa" },
  { code: "NZ", name: "New Zealand", dialCode: "64", currency: "NZD", continent: "Oceania" },
  { code: "IE", name: "Ireland", dialCode: "353", currency: "EUR", continent: "Europe" },
  { code: "DE", name: "Germany", dialCode: "49", currency: "EUR", continent: "Europe" },
  { code: "FR", name: "France", dialCode: "33", currency: "EUR", continent: "Europe" },
  { code: "NL", name: "Netherlands", dialCode: "31", currency: "EUR", continent: "Europe" },
  { code: "ES", name: "Spain", dialCode: "34", currency: "EUR", continent: "Europe" },
  { code: "IT", name: "Italy", dialCode: "39", currency: "EUR", continent: "Europe" },
  { code: "PT", name: "Portugal", dialCode: "351", currency: "EUR", continent: "Europe" },
  { code: "CH", name: "Switzerland", dialCode: "41", currency: "CHF", continent: "Europe" },
  { code: "BE", name: "Belgium", dialCode: "32", currency: "EUR", continent: "Europe" },
  { code: "AT", name: "Austria", dialCode: "43", currency: "EUR", continent: "Europe" },
  { code: "SE", name: "Sweden", dialCode: "46", currency: "SEK", continent: "Europe" },
  { code: "NO", name: "Norway", dialCode: "47", currency: "NOK", continent: "Europe" },
  { code: "DK", name: "Denmark", dialCode: "45", currency: "DKK", continent: "Europe" },
  { code: "FI", name: "Finland", dialCode: "358", currency: "EUR", continent: "Europe" },
  { code: "PL", name: "Poland", dialCode: "48", currency: "PLN", continent: "Europe" },
  { code: "GR", name: "Greece", dialCode: "30", currency: "EUR", continent: "Europe" },
  { code: "CZ", name: "Czech Republic", dialCode: "420", currency: "CZK", continent: "Europe" },
  { code: "HU", name: "Hungary", dialCode: "36", currency: "HUF", continent: "Europe" },
  { code: "RO", name: "Romania", dialCode: "40", currency: "RON", continent: "Europe" },
  { code: "BG", name: "Bulgaria", dialCode: "359", currency: "BGN", continent: "Europe" },
  { code: "HR", name: "Croatia", dialCode: "385", currency: "EUR", continent: "Europe" },
  { code: "RS", name: "Serbia", dialCode: "381", currency: "RSD", continent: "Europe" },
  { code: "UA", name: "Ukraine", dialCode: "380", currency: "UAH", continent: "Europe" },
  { code: "TR", name: "Turkey", dialCode: "90", currency: "TRY", continent: "Asia" },
  { code: "RU", name: "Russia", dialCode: "7", currency: "RUB", continent: "Europe" },
  { code: "JP", name: "Japan", dialCode: "81", currency: "JPY", continent: "Asia" },
  { code: "KR", name: "South Korea", dialCode: "82", currency: "KRW", continent: "Asia" },
  { code: "CN", name: "China", dialCode: "86", currency: "CNY", continent: "Asia" },
  { code: "HK", name: "Hong Kong", dialCode: "852", currency: "HKD", continent: "Asia" },
  { code: "TW", name: "Taiwan", dialCode: "886", currency: "TWD", continent: "Asia" },
  { code: "TH", name: "Thailand", dialCode: "66", currency: "THB", continent: "Asia" },
  { code: "MY", name: "Malaysia", dialCode: "60", currency: "MYR", continent: "Asia" },
  { code: "ID", name: "Indonesia", dialCode: "62", currency: "IDR", continent: "Asia" },
  { code: "PH", name: "Philippines", dialCode: "63", currency: "PHP", continent: "Asia" },
  { code: "VN", name: "Vietnam", dialCode: "84", currency: "VND", continent: "Asia" },
  { code: "PK", name: "Pakistan", dialCode: "92", currency: "PKR", continent: "Asia" },
  { code: "BD", name: "Bangladesh", dialCode: "880", currency: "BDT", continent: "Asia" },
  { code: "LK", name: "Sri Lanka", dialCode: "94", currency: "LKR", continent: "Asia" },
  { code: "NP", name: "Nepal", dialCode: "977", currency: "NPR", continent: "Asia" },
  { code: "BH", name: "Bahrain", dialCode: "973", currency: "BHD", continent: "Asia" },
  { code: "KW", name: "Kuwait", dialCode: "965", currency: "KWD", continent: "Asia" },
  { code: "QA", name: "Qatar", dialCode: "974", currency: "QAR", continent: "Asia" },
  { code: "OM", name: "Oman", dialCode: "968", currency: "OMR", continent: "Asia" },
  { code: "SA", name: "Saudi Arabia", dialCode: "966", currency: "SAR", continent: "Asia" },
  { code: "JO", name: "Jordan", dialCode: "962", currency: "JOD", continent: "Asia" },
  { code: "LB", name: "Lebanon", dialCode: "961", currency: "LBP", continent: "Asia" },
  { code: "IL", name: "Israel", dialCode: "972", currency: "ILS", continent: "Asia" },
  { code: "EG", name: "Egypt", dialCode: "20", currency: "EGP", continent: "Africa" },
  { code: "MA", name: "Morocco", dialCode: "212", currency: "MAD", continent: "Africa" },
  { code: "GH", name: "Ghana", dialCode: "233", currency: "GHS", continent: "Africa" },
  { code: "TZ", name: "Tanzania", dialCode: "255", currency: "TZS", continent: "Africa" },
  { code: "UG", name: "Uganda", dialCode: "256", currency: "UGX", continent: "Africa" },
  { code: "ET", name: "Ethiopia", dialCode: "251", currency: "ETB", continent: "Africa" },
  { code: "BR", name: "Brazil", dialCode: "55", currency: "BRL", continent: "South America" },
  { code: "AR", name: "Argentina", dialCode: "54", currency: "ARS", continent: "South America" },
  { code: "CL", name: "Chile", dialCode: "56", currency: "CLP", continent: "South America" },
  { code: "CO", name: "Colombia", dialCode: "57", currency: "COP", continent: "South America" },
  { code: "PE", name: "Peru", dialCode: "51", currency: "PEN", continent: "South America" },
  { code: "MX", name: "Mexico", dialCode: "52", currency: "MXN", continent: "North America" },
  { code: "JM", name: "Jamaica", dialCode: "1", currency: "JMD", continent: "North America" },
  { code: "TT", name: "Trinidad and Tobago", dialCode: "1", currency: "TTD", continent: "North America" },
];

/** Get country info by ISO code */
export function getCountryByCode(code: string): CountryInfo | undefined {
  return COUNTRIES.find(c => c.code === code);
}

/** Currency symbol mapping */
export const CURRENCY_SYMBOLS: Record<string, string> = {
  INR: "₹",
  USD: "$",
  GBP: "£",
  AED: "AED",
  AUD: "A$",
  CAD: "CA$",
  SGD: "S$",
  ZAR: "R",
  NGN: "₦",
  KES: "KSh",
  NZD: "NZ$",
  EUR: "€",
  CHF: "CHF",
  SEK: "kr",
  NOK: "kr",
  DKK: "kr",
  PLN: "zł",
  CZK: "Kč",
  HUF: "Ft",
  RON: "lei",
  BGN: "лв",
  RSD: "дин",
  UAH: "₴",
  RUB: "₽",
  TRY: "₺",
  JPY: "¥",
  KRW: "₩",
  CNY: "¥",
  HKD: "HK$",
  TWD: "NT$",
  THB: "฿",
  MYR: "RM",
  IDR: "Rp",
  PHP: "₱",
  VND: "₫",
  PKR: "₨",
  BDT: "৳",
  LKR: "Rs",
  NPR: "₨",
  BHD: "BHD",
  KWD: "KWD",
  QAR: "QAR",
  OMR: "OMR",
  SAR: "SAR",
  JOD: "JOD",
  LBP: "LBP",
  ILS: "₪",
  EGP: "E£",
  MAD: "DH",
  GHS: "₵",
  TZS: "TSh",
  UGX: "USh",
  ETB: "Br",
  BRL: "R$",
  ARS: "$",
  CLP: "$",
  COP: "$",
  PEN: "S/",
  MXN: "$",
  JMD: "J$",
  TTD: "TT$",
};
