const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient({ datasources: { db: { url: 'postgresql://postgres.kcqygvzxgkvwlupoyzzw:Jesuslovesyou%401406@aws-1-ap-south-1.pooler.supabase.com:6543/postgres?pgbouncer=true&connection_limit=1' } } });

const categories = [
  { slug:'wedding-cakes', label:'Wedding Cakes', ecosystem:'FINDMYBITES', description:'Custom wedding cakes and celebration centrepieces for your special day', icon:'Cake', accent:'from-rose-400 to-red-500', subs:['Tiered Wedding Cakes','Fondant & Sugar Art Cakes','Naked & Semi-Naked Cakes','Floral Wedding Cakes','Traditional Fruit Cakes','Vegan Wedding Cakes','Gluten-Free Wedding Cakes','Custom Sculpted Cakes'] },
  { slug:'birthday-celebration-cakes', label:'Birthday & Celebration Cakes', ecosystem:'FINDMYBITES', description:'Personalised cakes for birthdays, anniversaries and every celebration', icon:'Cake', accent:'from-amber-400 to-orange-500', subs:['Birthday Cakes (Adults)','Kids Birthday Cakes','Number & Letter Cakes','Photo Cakes','Character & Theme Cakes','Smash Cakes','Pull-Apart Cupcake Cakes','Anniversary Cakes'] },
  { slug:'cupcakes-mini-desserts', label:'Cupcakes & Mini Desserts', ecosystem:'FINDMYBITES', description:'Gourmet cupcakes, cake pops and mini dessert collections', icon:'Cookie', accent:'from-pink-400 to-rose-500', subs:['Wedding Cupcakes','Birthday Cupcakes','Corporate Cupcakes','Themed Cupcake Sets','Cake Pops','Mini Cheesecakes','Dessert Boxes','Macarons & Petit Fours'] },
  { slug:'home-bakers-artisan-bread', label:'Home Bakers & Artisan Bread', ecosystem:'FINDMYBITES', description:'Artisan breads, pastries and baked goods crafted fresh from home kitchens', icon:'Wheat', accent:'from-amber-500 to-yellow-600', subs:['Sourdough Bread','Bagels','Croissants & Pastries','Bread & Loaves','Gluten-Free Baked Goods','Vegan Baked Goods','Sandwich Bread','Focaccia & Flatbreads'] },
  { slug:'desserts-sweets', label:'Desserts & Sweets', ecosystem:'FINDMYBITES', description:'Traditional and contemporary desserts from around the world', icon:'IceCream', accent:'from-purple-400 to-pink-500', subs:['Arabic & Middle Eastern Sweets','Indian Mithai & Sweets','Turkish Desserts','French Patisserie','Italian Desserts','Chocolate & Truffles','Ice Cream & Gelato','Cheesecakes','Brownies & Bars','Puddings & Trifles'] },
  { slug:'wedding-event-catering', label:'Wedding & Event Catering', ecosystem:'FINDMYBITES', description:'Full-service catering for weddings, receptions and large celebrations', icon:'UtensilsCrossed', accent:'from-rose-400 to-red-500', subs:['Wedding Buffet','Sit-Down Wedding Dinner','Cocktail & Canapes','Wedding Breakfast','Engagement Party Catering','Reception Catering','Traditional Wedding Feasts','Live Cooking Stations'] },
  { slug:'corporate-catering', label:'Corporate Catering', ecosystem:'FINDMYBITES', description:'Professional catering solutions for offices, meetings and corporate events', icon:'Briefcase', accent:'from-blue-400 to-indigo-500', subs:['Office Lunch Delivery','Meeting & Conference Catering','Corporate Breakfast','Team Building BBQ','Product Launch Catering','Award Ceremony Catering','Corporate Canapes','Networking Event Catering'] },
  { slug:'private-chefs', label:'Private Chefs', ecosystem:'FINDMYBITES', description:'Professional chefs who cook in your home or venue for intimate dining experiences', icon:'ChefHat', accent:'from-emerald-400 to-teal-500', subs:['Private Dinner Experience','Meal Prep & Weekly Cooking','Cooking Classes (Private)','Pop-Up Restaurant Experience','Chef for Holidays & Travel','Couples Dining Experience','Family Meal Service','Luxury Yacht & Villa Chef'] },
  { slug:'food-trucks-street-food', label:'Food Trucks & Street Food', ecosystem:'FINDMYBITES', description:'Mobile food vendors bringing street food flavours to your event', icon:'Truck', accent:'from-orange-400 to-red-500', subs:['Burger & BBQ Trucks','Taco & Mexican Street Food','Asian Street Food','Middle Eastern Street Food','African Street Food','Pizza & Italian Street Food','Vegan Street Food','Dessert Trucks','Coffee & Drinks Trucks'] },
  { slug:'breakfast-brunch-catering', label:'Breakfast & Brunch Catering', ecosystem:'FINDMYBITES', description:'Morning catering for brunches, baby showers and breakfast events', icon:'Coffee', accent:'from-amber-400 to-yellow-500', subs:['Brunch Buffet','Baby Shower Catering','Grazing Tables & Boards','Continental Breakfast','Middle Eastern Breakfast','English Breakfast Catering','Waffle & Pancake Stations','Smoothie & Juice Bars'] },
  { slug:'halal-catering', label:'Halal Catering', ecosystem:'FINDMYBITES', description:'Fully certified Halal catering for all occasions and dietary requirements', icon:'UtensilsCrossed', accent:'from-green-400 to-emerald-500', subs:['Halal Wedding Catering','Halal Corporate Catering','Halal BBQ & Grill','Halal Home Cooking','Halal Buffet Service','Halal Street Food','Halal Desserts & Sweets','Halal Meal Prep'] },
  { slug:'vegan-plant-based', label:'Vegan & Plant-Based', ecosystem:'FINDMYBITES', description:'100% plant-based catering and baked goods for health-conscious celebrations', icon:'Leaf', accent:'from-green-400 to-teal-500', subs:['Vegan Wedding Catering','Vegan Cakes & Desserts','Raw Food Catering','Vegan Street Food','Plant-Based Meal Prep','Vegan Corporate Catering','Vegan Grazing Boards','Dairy-Free Specialists'] },
  { slug:'world-cuisines', label:'World Cuisines', ecosystem:'FINDMYBITES', description:'Authentic cuisine specialists from every corner of the globe', icon:'Globe', accent:'from-blue-400 to-purple-500', subs:['Indian & South Asian','Arabic & Levantine','West African & Nigerian','East African','Japanese & Korean','Chinese & Dim Sum','Thai & Southeast Asian','Mediterranean','Mexican & Latin American','Caribbean','Persian & Iranian','Turkish & Ottoman','Ethiopian & East African','Greek & Cypriot'] },
  { slug:'grazing-tables-boards', label:'Grazing Tables & Boards', ecosystem:'FINDMYBITES', description:'Stunning grazing tables, charcuterie boards and sharing platters', icon:'Cheese', accent:'from-amber-400 to-orange-500', subs:['Charcuterie & Cheese Boards','Mezze & Dip Platters','Fruit & Sweet Grazing Tables','Wedding Grazing Tables','Corporate Grazing Boards','Kids Party Grazing','Vegan Grazing Boards','Luxury Seafood Platters'] },
  { slug:'meal-prep-delivery', label:'Meal Prep & Delivery', ecosystem:'FINDMYBITES', description:'Weekly meal preparation and healthy food delivery services', icon:'Package', accent:'from-teal-400 to-cyan-500', subs:['Weekly Meal Plans','Healthy & Diet Meals','Post-Natal Meal Delivery','Athlete & Fitness Meals','Keto & Low-Carb Meals','Family Meal Boxes','Office Lunch Subscriptions','Baby & Toddler Meals'] },
  { slug:'drinks-beverages', label:'Drinks & Beverages', ecosystem:'FINDMYBITES', description:'Specialist drink services for events and celebrations', icon:'Wine', accent:'from-purple-400 to-pink-500', subs:['Mobile Bar Service','Cocktail Catering','Non-Alcoholic Mocktails','Arabic Coffee & Tea Service','Juice & Smoothie Bars','Coffee Cart & Barista','Hot Chocolate & Dessert Drinks','Champagne & Wine Service'] },
  { slug:'chocolate-confectionery', label:'Chocolate & Confectionery', ecosystem:'FINDMYBITES', description:'Luxury chocolates, sweet tables and confectionery for gifts and events', icon:'Cookie', accent:'from-amber-600 to-orange-700', subs:['Luxury Chocolate Boxes','Wedding Favours (Sweet)','Chocolate Fountains','Sweet Tables & Candy Bars','Personalised Chocolates','Arabic & Turkish Sweets','Fudge & Toffee','Lollipops & Hard Candy'] },
  { slug:'event-planning-coordination', label:'Event Planning & Coordination', ecosystem:'PIMPMYPARTY', description:'Professional event planners and coordinators for every type of celebration', icon:'ClipboardList', accent:'from-fuchsia-500 to-purple-600', subs:['Full Wedding Planning','Day-of Coordination','Birthday Party Planning','Corporate Event Management','Baby Shower Planning','Kids Party Planning','Engagement Party Planning','Destination Event Planning'] },
  { slug:'wedding-decoration-styling', label:'Wedding Decoration & Styling', ecosystem:'PIMPMYPARTY', description:'Complete wedding decoration and venue styling services', icon:'Flower', accent:'from-rose-400 to-pink-500', subs:['Full Venue Decoration','Ceremony Arch & Backdrop','Table Centrepieces','Floral Wall & Installations','Lighting Design','Fairy Light & Draping','Chair & Linen Styling','Entrance & Aisle Decoration'] },
  { slug:'birthday-party-decoration', label:'Birthday & Party Decoration', ecosystem:'PIMPMYPARTY', description:'Fun and creative decoration for birthdays and celebration parties', icon:'PartyPopper', accent:'from-fuchsia-400 to-pink-500', subs:['Balloon Decoration','Balloon Arches & Columns','Themed Party Decoration','Backdrop & Photo Booth Setup','Kids Party Decoration','Neon Signs & Letters','Table Balloon Displays','Gender Reveal Decoration'] },
  { slug:'photography', label:'Photography', ecosystem:'PIMPMYPARTY', description:'Professional photographers capturing your most precious moments', icon:'Camera', accent:'from-blue-400 to-indigo-500', subs:['Wedding Photography','Engagement Photography','Birthday Party Photography','Corporate Event Photography','Family Portrait Sessions','Newborn Photography','Product Photography','Headshots & Professional Portraits'] },
  { slug:'videography-film', label:'Videography & Film', ecosystem:'PIMPMYPARTY', description:'Cinematic videographers creating lasting memories of your events', icon:'Video', accent:'from-indigo-400 to-purple-500', subs:['Wedding Videography','Highlight Reel & Short Films','Drone Videography','Corporate Video Production','Social Media Content Creation','Live Streaming Services','Music Videos','Documentary Style Coverage'] },
  { slug:'djs-music', label:'DJs & Music', ecosystem:'PIMPMYPARTY', description:'Professional DJs and live music for events of every size', icon:'Music', accent:'from-purple-400 to-fuchsia-500', subs:['Wedding DJ','Birthday Party DJ','Corporate Event DJ','Kids Party DJ','Club & Festival DJ','Arabic Music DJ','Bollywood DJ','Live Band & Musicians'] },
  { slug:'florists-floral-design', label:'Florists & Floral Design', ecosystem:'PIMPMYPARTY', description:'Stunning floral arrangements and designs for weddings and events', icon:'Flower2', accent:'from-rose-400 to-green-500', subs:['Wedding Bouquets & Florals','Event Centrepieces','Flower Walls & Installations','Corporate Flower Subscriptions','Sympathy & Funeral Flowers','Birthday Flower Arrangements','Dried Flower Arrangements','Luxury Exotic Flowers'] },
  { slug:'venues-spaces', label:'Venues & Spaces', ecosystem:'PIMPMYPARTY', description:'Unique venues and event spaces for every type of occasion', icon:'Building2', accent:'from-slate-400 to-gray-500', subs:['Wedding Venues','Birthday Party Venues','Corporate Event Spaces','Outdoor & Garden Venues','Rooftop Venues','Beach & Waterfront Venues','Private Dining Rooms','Virtual Event Platforms'] },
  { slug:'kids-entertainment', label:'Kids Entertainment', ecosystem:'PIMPMYPARTY', description:'Specialist entertainers making childrens parties magical and memorable', icon:'Baby', accent:'from-yellow-400 to-orange-500', subs:['Magic Shows','Face Painting','Bouncy Castles & Inflatables','Character Appearances','Balloon Twisting','Soft Play Equipment','Kids Disco & DJ','Science & Educational Shows','Clowns & Jesters','Puppet Shows'] },
  { slug:'photo-booths-experiences', label:'Photo Booths & Experiences', ecosystem:'PIMPMYPARTY', description:'Interactive photo experiences and entertainment for guests', icon:'Camera', accent:'from-pink-400 to-purple-500', subs:['Classic Photo Booth','Open Air Photo Booth','Mirror Photo Booth','360 Video Booth','Glam Cam & Slow Motion','Green Screen Booth','Vintage Film Camera Booth','Digital & GIF Booths'] },
  { slug:'hair-makeup', label:'Hair & Makeup', ecosystem:'PIMPMYPARTY', description:'Professional beauty services for brides, events and special occasions', icon:'Scissors', accent:'from-rose-400 to-pink-500', subs:['Bridal Hair & Makeup','Wedding Party Makeup','Prom & Formal Makeup','Editorial & Photoshoot','Airbrush Makeup','Traditional Bridal (Henna etc)','Mobile Hair Styling','Lashes & Brow Services'] },
  { slug:'henna-cultural-arts', label:'Henna & Cultural Arts', ecosystem:'PIMPMYPARTY', description:'Traditional henna and cultural beauty arts for weddings and celebrations', icon:'Hand', accent:'from-amber-500 to-orange-600', subs:['Bridal Henna (Mehndi)','Party Henna','Arabic Henna Designs','Indian Mehndi','Henna for Kids','Body Art & Temporary Tattoos','Cultural Face Painting','Mandala & Geometric Henna'] },
  { slug:'lighting-av-production', label:'Lighting & AV Production', ecosystem:'PIMPMYPARTY', description:'Professional lighting and audio visual production for events', icon:'Lightbulb', accent:'from-yellow-400 to-amber-500', subs:['Wedding Lighting Design','Uplighting & Ambiance','Gobo & Monogram Projections','Stage & Concert Lighting','PA Systems & Sound','LED Dance Floors','Projection Mapping','Truss & Rigging'] },
  { slug:'mc-hosts', label:'MC & Hosts', ecosystem:'PIMPMYPARTY', description:'Charismatic MCs and event hosts keeping your event flowing perfectly', icon:'Mic', accent:'from-indigo-400 to-blue-500', subs:['Wedding MC','Corporate Event Host','Awards Ceremony MC','Bilingual MC (Arabic/English)','Comedy MC & Roast Host','Kids Party Host','Trivia & Game Show Host','Conference Facilitator'] },
  { slug:'transport-transfers', label:'Transport & Transfers', ecosystem:'PIMPMYPARTY', description:'Luxury and themed transport for weddings and special occasions', icon:'Car', accent:'from-slate-400 to-blue-500', subs:['Wedding Car Hire','Vintage & Classic Cars','Limousine Service','Party Bus','Horse & Carriage','Helicopter Transfers','Luxury Coach Hire','Guest Shuttle Service'] },
  { slug:'printing-stationery', label:'Printing & Stationery', ecosystem:'PIMPMYPARTY', description:'Beautiful wedding and event stationery and printed materials', icon:'Printer', accent:'from-gray-400 to-slate-500', subs:['Wedding Invitations','Save the Dates','Menu Cards & Place Cards','Order of Service','Thank You Cards','Custom Event Signage','Seating Charts','Wedding Favours (Printed)'] },
  { slug:'entertainment-performers', label:'Entertainment & Performers', ecosystem:'PIMPMYPARTY', description:'Unique entertainment acts and performers for unforgettable events', icon:'Sparkles', accent:'from-fuchsia-500 to-pink-600', subs:['Caricature Artists','Magicians & Illusionists','Fire & Aerial Performers','Live Painters','Dancers & Dance Troupes','Comedy Acts & Comedians','Acrobats & Circus Acts','Cultural Performers'] },
  { slug:'cakes-desserts-events', label:'Cakes & Desserts for Events', ecosystem:'PIMPMYPARTY', description:'Celebration cakes and dessert tables for parties and events', icon:'Cake', accent:'from-pink-400 to-rose-500', subs:['Party Cake Collection','Dessert Tables & Stations','Candy Buffets','Donut Walls','Crepe & Waffle Stations','Ice Cream Carts','Popcorn & Snack Carts','Cotton Candy Stations'] },
];

async function main() {
  // Clear existing
  await prisma.subcategory.deleteMany({});
  await prisma.category.deleteMany({});
  console.log('Old categories cleared ✅');

  let catCount = 0, subCount = 0;
  const usedSubSlugs = new Set();
  
  for (let i = 0; i < categories.length; i++) {
    const c = categories[i];
    const created = await prisma.category.create({
      data: { slug: c.slug, label: c.label, ecosystem: c.ecosystem, description: c.description, icon: c.icon, accent: c.accent, image: `/vendors/${c.slug}.png`, sortOrder: i, active: true }
    });
    catCount++;

    for (let j = 0; j < c.subs.length; j++) {
      let subSlug = c.subs[j].toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
      // Ensure unique slug
      if (usedSubSlugs.has(subSlug)) subSlug = `${subSlug}-${c.slug.split('-')[0]}`;
      usedSubSlugs.add(subSlug);
      
      await prisma.subcategory.create({
        data: { slug: subSlug, label: c.subs[j], categoryId: created.id, sortOrder: j, active: true }
      });
      subCount++;
    }
  }

  console.log(`Inserted ${catCount} categories and ${subCount} subcategories ✅`);
  const food = await prisma.category.count({ where: { ecosystem: 'FINDMYBITES' } });
  const party = await prisma.category.count({ where: { ecosystem: 'PIMPMYPARTY' } });
  const totalSubs = await prisma.subcategory.count();
  console.log(`Verify: FINDMYBITES=${food}, PIMPMYPARTY=${party}, Subcategories=${totalSubs}`);
}
main().catch(e => { console.error(e.message); process.exit(1); }).finally(() => prisma.$disconnect());
